# Generated by Django 4.1.6 on 2023-02-18 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_all_ingredients'),
    ]

    operations = [
        migrations.AddField(
            model_name='list_of_dish',
            name='image_path',
            field=models.ImageField(default='images/default.jpg', upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='list_of_dish',
            name='image',
            field=models.ImageField(upload_to='images/', verbose_name='Image'),
        ),
    ]
