# Generated by Django 4.1.6 on 2023-02-18 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_alter_list_of_dish_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='list_of_dish',
            name='image',
            field=models.ImageField(max_length=255, upload_to='media/images/', verbose_name='Image'),
        ),
    ]
