# Generated by Django 4.1.5 on 2023-03-03 15:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_list_of_dish_image_path_list_of_dish_image_path720_and_more'),
        ('base', '0009_rename_image720_path_list_of_dish_image_path720'),
    ]

    operations = [
    ]
