# Generated by Django 4.1.6 on 2023-03-04 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0010_merge_20230303_1502'),
    ]

    operations = [
        migrations.AlterField(
            model_name='list_of_dish',
            name='image',
            field=models.TextField(blank=True, verbose_name='Image'),
        ),
    ]
