# Generated by Django 4.1.5 on 2023-03-05 11:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0012_list_of_dish_created_by_list_of_dish_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reviews',
            old_name='movie',
            new_name='dish',
        ),
    ]
