# Generated by Django 4.1.5 on 2023-03-05 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0014_remove_reviews_email_remove_reviews_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='list_of_dish',
            name='rating',
            field=models.SmallIntegerField(default=0),
        ),
    ]
