# Generated by Django 4.1.5 on 2023-03-05 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0015_list_of_dish_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='list_of_dish',
            name='rating',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True),
        ),
    ]
