# Generated by Django 4.1.5 on 2023-03-20 20:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0022_delete_like'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='list_of_dish',
            name='image',
        ),
        migrations.RemoveField(
            model_name='list_of_dish',
            name='image_path',
        ),
        migrations.RenameField(
            model_name='list_of_dish',
            old_name='image_path720',
            new_name='image',
        ),
    ]
